(function () {
  // STAFF_DATA is now fetched from Supabase.
  // We keep it empty here to ensure no data is leaked in the client-side code.
  window.STAFF_DATA = {};

  // DEFAULT_DATA is now fetched from Supabase.
  // We keep the structure for UI groups but set values to 0.
  // Real values will be synced on app boot.
  window.DEFAULT_DATA = {
    UIR: {
      w: 640,
      h: 480,
      weight: 7.8,
      type: "indoor",
      items: [],
    },
    UOS: {
      w: 960,
      h: 960,
      weight: 26.5,
      type: "outdoor",
      items: [],
    },
    CIH: {
      w: 600,
      h: 337.5,
      weight: 4.0,
      type: "indoor",
      items: [],
    },
    controllers: [],
    accessories: [],
  };

  window.I18N = {
    th: {
      appTitle: "RAZR LED Solution Calculator Pro",
      subtitle: "คำนวณสเปก, ราคา, และจัดการสินค้าได้จากหน้า Admin",
      quoteSub: "ระบบจัดทำใบเสนอราคา LED — RAZR Solution",
      adminLogin: "Login Admin",
      adminLogout: "ออกจากระบบ",
      adminOn: "ล็อกอินแล้ว",
      adminOff: "ยังไม่ล็อกอิน",
      tab1: "UIRx/c (640x480)",
      tab2: "UOSx (960x960)",
      tab3: "CIH (600x337.5)",
      selectLed: "เลือกรุ่น LED Display",
      qtyW: "จำนวนตู้ (แนวนอน)",
      qtyH: "จำนวนตู้ (แนวตั้ง)",
      controller: "เลือก Controller",
      extraController: "Controller เพิ่มเติม",
      accessories: "อุปกรณ์เสริม",
      totalPrice: "ราคารวมสุทธิ",
      totalPixels: "จำนวนพิกเซลรวม",
      totalWeight: "น้ำหนักจอรวม",
      totalMaxPower: "การกินไฟ (Typical / Max)",
      totalCurrent: "กระแสไฟฟ้า (รวมกระแสเกิน 1.25x)",
      powerCost: "ค่าไฟโดยประมาณ (5 บาท/หน่วย)",
      ledPrice: "ค่าสินค้า LED",
      installPrice: "ค่าติดตั้งโดยประมาณ",
      controllerPrice: "ค่า Controller",
      unitBaht: "บาท",
      unitKg: "kg",
      unitWatts: "Watts",
      unitAmp: "A",
      unitHour: "ชม.",
      calculating: "กำลังคำนวณ...",
      noMatchingController: "Controller ไม่พอสำหรับขนาดนี้",
      reset: "รีเซ็ตข้อมูล",
      backHome: "กลับหน้า Calculator",
      dashboardHome: "กลับหน้าแรก",
      adminTitle: "Admin: จัดการ Master Data",
      adminSub:
        "แก้ไขสินค้า/Controller ได้ทันที และบันทึกลงฐานข้อมูลของเบราว์เซอร์",
      targetGroup: "เลือกหมวดที่ต้องการแก้ไข",
      addRow: "+ เพิ่มแถวใหม่",
      saveAll: "บันทึกทั้งหมด",
      resetToDefault: "รีเซ็ตเป็นค่าเริ่มต้น",
      adminPanelInfo: "แก้ไขข้อมูลในตารางได้ทันที ระบบจะบันทึกให้อัตโนมัติ",
      confirmReset:
        "คุณแน่ใจหรือไม่ว่าต้องการรีเซ็ตข้อมูลทั้งหมดกลับเป็นค่าเริ่มต้น?",
      resetDone: "รีเซ็ตข้อมูลเรียบร้อยแล้ว",
      confirmDelete: "ลบรายการนี้ใช่หรือไม่?",
      confirmDeleteCon: "ลบ Controller นี้ใช่หรือไม่?",
      saved: "บันทึกข้อมูลเรียบร้อยแล้ว",
      loginTitle: "Admin Login",
      loginDesc: "ล็อกอินนี้เก็บไว้ในโค้ด ไม่ต้องใช้ฐานข้อมูล",
      username: "Username",
      password: "Password",
      loginBtn: "เข้าสู่ระบบ",
      cancel: "ยกเลิก",
      loginOk: "เข้าสู่ระบบสำเร็จ",
      loginFail: "Username หรือ Password ไม่ถูกต้อง",
      lang: "TH / EN",
      theme: "ธีม",
      light: "สว่าง",
      dark: "มืด",
      themeLabel: "ธีม: สว่าง",
      priceMode: "ราคา: มาตรฐาน",
      priceStandard: "ราคามาตรฐาน",
      priceCustom: "กำหนดราคาเอง",
      customPriceLabel: "ราคา LED ต่อ ตร.ม.",
      customInstallLabel: "ค่าติดตั้งจอ",
      customSteelLabel: "ค่าโครงสร้างเหล็กรับจอ",
      customAlumLabel: "Aluminium Composite",
      customLoadCabLabel: "ค่าติดตั้งตู้โหลดไฟฟ้า",
      customCableLabel: "ค่าติดตั้งสายสัญญาณ",
      customDemoLabel: "ค่ารื้อถอน",
      customFoundLabel: "ค่าฝังฐานราก",
      customExtraPlaceholder: "ไม่ระบุ = 0",
      name: "ชื่อรุ่น",
      rw: "พิกเซล (W)",
      rh: "พิกเซล (H)",
      max: "กินไฟ Max (W)",
      avg: "กินไฟ Avg (W)",
      pricePerCab: "ราคา/ตร.ม.",
      controllerName: "ชื่อ Controller",
      load: "โหลดพิกเซล",
      price: "ราคา",
      accName: "ชื่ออุปกรณ์",
      manage: "จัดการ",
      delete: "ลบ",
      areaLabel: "พื้นที่จอภาพ",
      resolutionLabel: "ความละเอียด",
      actualSizeLabel: "ขนาดจอ (กว้าง x สูง)",
      sqm: "ตร.ม.",
      pixels: "Pixels",
      quoteBtn: "ทำใบเสนอราคา",
      comingSoon: "ฟีเจอร์นี้กำลังเปิดให้บริการเร็วๆ นี้",
      unitPriceSqm: "ราคา/ตร.ม.",
      unitPriceController: "ราคา/ตัว",
      unitPriceAccessory: "ราคา/ชิ้น",
      exact16_9: "Exactly 16:9",
      wider16_9: "Close to 16:9 (Slightly wider)",
      taller16_9: "Close to 16:9 (Slightly taller)",
      exact16_10: "Exactly 16:10",
      wider16_10: "Close to 16:10 (Slightly wider)",
      taller16_10: "Close to 16:10 (Slightly taller)",
      exact21_9: "Exactly 21:9",
      wider21_9: "Close to 21:9 (Slightly wider)",
      taller21_9: "Close to 21:9 (Slightly taller)",
      ratioRaw: "Raw Ratio",
      empId: "รหัสพนักงาน",
      exampleId: "รหัสตัวอย่าง:",
      loginTitlePage: "พนักงานเข้าสู่ระบบ",
      welcome: "ยินดีต้อนรับ",
      invalidId: "รหัสพนักงานไม่ถูกต้อง",
      dept: "แผนก",
      detailBtn: "รายละเอียด(Demo)",
      copyBtn: "คัดลอกผลลัพธ์",
      copySuccess: "คัดลอกผลลัพธ์แล้ว",
      copyError: "เกิดข้อผิดพลาดในการคัดลอก",
      anonHome: "หน้าหลัก (ไม่ระบุตัวตน)",
      screenSize: "ขนาดจอภาพ",
      unitMeter: "เมตร",
      aspectRatio: "สัดส่วนจอ",
      area: "พื้นที่จอ",
      unitSqM: "ตร.ม.",
      resolution: "ความละเอียด",
      pixels: "พิกเซล",
      weight: "น้ำหนักจอ",
      power: "การกินไฟ",
      amps: "กระแสไฟ",
      unitAmps: "แอมป์ (A)",
      unitPixels: "px",
      elecCost: "ค่าไฟโดยประมาณ",
      perHour: "ต่อชั่วโมง",
      productPrice: "ค่าสินค้า (LED)",
      notQuoted: "กรุณาติดต่อฝ่ายขาย",
      notQuoted2: "N/A",
      installPrice: "ค่าติดตั้งเบื้องต้น",
      controllerPrice: "ค่าสินค้า (Controller)",
      na: "N/A",
      extraConLabel: "คอนโทรลเลอร์เพิ่มเติม",
      accLabel: "อุปกรณ์เสริม",
      total: "รวมทั้งสิ้น",
      none: "-- ไม่รับ --",
      recommend: "แนะนำรุ่นที่เหมาะสม:",
      noEnough: "ไม่มีรุ่นที่รองรับขนาดนี้",
      recText: "ระบบแนะนำรุ่นที่เหมาะสม",
      ratioRaw: "สัดส่วนจริง",
      makeQuote: "ทำใบเสนอราคา",
      totalCabLabel: "จำนวนตู้ที่ใช้",
      diagonalLabel: "ขนาดจอนิ้ว (แนวทแยง)",
      unitInch: "นิ้ว",
      unitUnits: "ตู้",
      comingSoonDesc:
        "ระบบจัดทำใบเสนอราคาอัตโนมัติ กำลังอยู่ระหว่างการพัฒนา เร็วๆ นี้คุณจะสามารถสร้างใบเสนอราคาได้อย่างง่ายดาย",
      developing: "กำลังพัฒนา...",
      backToCalc: "← กลับไปคำนวณ LED",
      technicalSpecTitle: "ข้อมูลทางเทคนิค",
      groundLevel: "ระดับพื้นดิน",
      screenPanelDetails: "รายละเอียดจอภาพและพาเนล",
      productDetailsHeader: "รายละเอียดสินค้า",
      displayInfoHeader: "ข้อมูลการแสดงผล",
      paramHeader: "Parameter",
      valueHeader: "Value",
      pixelPitchLabel: "PX Pitch",
      brightnessLabel: "Brightness",
      ledTypeLabel: "LED Type",
      cabSizeLabel: "Cab. Size",
      cabResLabel: "Cab. Res.",
      modSizeLabel: "Mod. Size",
      modResLabel: "Mod. Res.",
      refreshRateLabel: "Refresh Rate",
      materialLabel: "วัสดุ",
      maintenanceLabel: "การบำรุงรักษา",
      cabWeightLabel: "Weight/Cab.",
      typPowerLabel: "Typ. Power",
      maxPowerLabel: "Max Power",
      panelWidthLabel: "Panel Width",
      panelHeightLabel: "Panel Height",
      totalPxLabel: "Total Pixels",
      pxDensityLabel: "PX Density",
      totalWeightLabel: "Total Weight",
      totalPowerLabel: "Total Power",
      displayResLabel: "Display Res.",
      unitMm: "มม.",
      unitHz: "Hz",
      unitCdSqm: "cd/m²",
      modeQty: "จำนวนตู้",
      modeSize: "เมตร (กว้าง*สูง)",
      qtyWPlaceholder: "เช่น 5",
      qtyHPlaceholder: "เช่น 4",
      widthPlaceholder: "กว้าง (เมตร)",
      heightPlaceholder: "สูง (เมตร)",
      customPricePlaceholder: "เช่น 6000",
      customInstallPlaceholder: "ไม่ระบุ = 0",
      qtyPlaceholder: "จำนวน",
      unitWidth: "กว้าง (เมตร)",
      unitHeight: "สูง (เมตร)",
      calcNoteTitle: "หมายเหตุ:",
      calcNoteDesc: "ราคาดังกล่าวเป็นราคารวมค่าติดตั้งและค่าใช้จ่ายอื่นๆ ที่เกี่ยวข้องแล้ว อย่างไรก็ตาม ราคานี้เป็นเพียงการประเมินเบื้องต้น อาจมีการเปลี่ยนแปลงได้ตามรายละเอียดหน้างานและเงื่อนไขเพิ่มเติม",
    },
    en: {
      appTitle: "RAZR LED Solution Calculator Pro",
      subtitle: "Calculate specs, prices, and manage data from Admin",
      quoteSub: "LED Quotation System — RAZR Solution",
      adminLogin: "Admin Login",
      adminLogout: "Logout",
      adminOn: "Logged In",
      adminOff: "Not Logged In",
      tab1: "UIRx/c (640x480)",
      tab2: "UOSx (960x960)",
      tab3: "CIH (600x337.5)",
      selectLed: "Select LED Display Model",
      qtyW: "Quantity (Width)",
      qtyH: "Quantity (Height)",
      controller: "Select Controller",
      extraController: "Extra Controller",
      accessories: "Accessories",
      totalPrice: "Net Total Price",
      totalPixels: "Total Pixels",
      totalWeight: "Total Screen Weight",
      totalMaxPower: "Power Consumption (Typical / Max)",
      totalCurrent: "Total Current (Incl. 1.25x Overload)",
      powerCost: "Estimated Power Cost (5 THB/Unit)",
      ledPrice: "LED Product Cost",
      installPrice: "Estimated Installation Cost",
      controllerPrice: "Controller Cost",
      unitBaht: "Baht",
      unitKg: "kg",
      unitWatts: "Watts",
      unitAmp: "A",
      unitHour: "hr.",
      calculating: "Calculating...",
      noMatchingController: "No matching controller for this size",
      reset: "Reset Data",
      backHome: "Back to Calculator",
      dashboardHome: "Back to Dashboard",
      adminTitle: "Admin: Manage Master Data",
      adminSub: "Edit products/controllers and save to browser database",
      targetGroup: "Select Category to Edit",
      addRow: "+ Add New Row",
      saveAll: "Save All",
      resetToDefault: "Reset to Default",
      adminPanelInfo: "Edit table data directly; system saves automatically",
      confirmReset: "Are you sure you want to reset all data to default?",
      resetDone: "Data reset successfully",
      confirmDelete: "Delete this item?",
      confirmDeleteCon: "Delete this controller?",
      saved: "Data saved successfully",
      loginTitle: "Admin Login",
      loginDesc: "Login credentials stored in code (no database required)",
      username: "Username",
      password: "Password",
      loginBtn: "Login",
      cancel: "Cancel",
      loginOk: "Login Successful",
      loginFail: "Invalid Username or Password",
      lang: "TH / EN",
      theme: "Theme",
      light: "Light",
      dark: "Dark",
      themeLabel: "Theme: Light",
      priceMode: "Price: Standard",
      priceStandard: "Standard Price",
      priceCustom: "Custom Price",
      customPriceLabel: "LED Price per sq.m.",
      customInstallLabel: "Display Installation",
      customSteelLabel: "Steel Structure",
      customAlumLabel: "Aluminium Composite",
      customLoadCabLabel: "Electrical Load Cabinet",
      customCableLabel: "Signal Cable Installation",
      customDemoLabel: "Demolition",
      customFoundLabel: "Foundation",
      customExtraPlaceholder: "Empty = 0",
      name: "Model Name",
      rw: "Pixels (W)",
      rh: "Pixels (H)",
      max: "Max Power (W)",
      avg: "Avg Power (W)",
      pricePerCab: "Price/sq.m.",
      controllerName: "Controller Name",
      load: "Pixel Load",
      price: "Price",
      accName: "Accessory Name",
      manage: "Actions",
      delete: "Delete",
      areaLabel: "Screen Area",
      resolutionLabel: "Resolution",
      actualSizeLabel: "Actual Size (W x H)",
      sqm: "sq.m.",
      pixels: "Pixels",
      quoteBtn: "Create Quotation",
      makeQuote: "Create Quotation",
      comingSoon: "This feature is coming soon",
      unitPriceSqm: "Price/sq.m.",
      unitPriceController: "Price/unit",
      unitPriceAccessory: "Price/piece",
      exact16_9: "Exactly 16:9",
      wider16_9: "Close to 16:9 (Slightly wider)",
      taller16_9: "Close to 16:9 (Slightly taller)",
      exact16_10: "Exactly 16:10",
      wider16_10: "Close to 16:10 (Slightly wider)",
      taller16_10: "Close to 16:10 (Slightly taller)",
      exact21_9: "Exactly 21:9",
      wider21_9: "Close to 21:9 (Slightly wider)",
      taller21_9: "Close to 21:9 (Slightly taller)",
      ratioRaw: "Raw Ratio",
      empId: "Employee ID",
      exampleId: "Example IDs:",
      loginTitlePage: "Employee Login",
      welcome: "Welcome",
      invalidId: "Invalid Employee ID",
      dept: "Dept",
      detailBtn: "Detail Spec (Demo)",
      copyBtn: "Copy Result",
      copySuccess: "Result copied to clipboard",
      copyError: "Failed to copy result",
      anonHome: "Home (Anonymous)",
      screenSize: "Screen Size",
      unitMeter: "m",
      aspectRatio: "Aspect Ratio",
      area: "Area",
      unitSqM: "sq.m.",
      resolution: "Resolution",
      pixels: "Pixels",
      weight: "Weight",
      power: "Power Consumption",
      amps: "Amps",
      unitAmps: "A",
      unitPixels: "px",
      elecCost: "Power Cost",
      perHour: "per hour",
      productPrice: "LED Product Price",
      notQuoted: "Contact Sales",
      notQuoted2: "N/A",
      installPrice: "Installation Price",
      controllerPrice: "Controller Price",
      na: "N/A",
      extraConLabel: "Extra Controller",
      accLabel: "Accessory",
      total: "Total",
      none: "-- No --",
      recommend: "Recommended Model:",
      noEnough: "No model found for this size",
      recText: "Smart Recommendation",
      ratioRaw: "Ratio",
      totalCabLabel: "Total Cabinets",
      diagonalLabel: "Screen Size (Diagonal)",
      unitInch: "in.",
      unitUnits: "Units",
      comingSoonDesc:
        "Automatic quotation system is under development. Soon you will be able to create quotes easily.",
      developing: "Developing...",
      backToCalc: "← Back to LED Calculator",
      technicalSpecTitle: "TECHNICAL SPECIFICATION",
      groundLevel: "GROUND LEVEL",
      screenPanelDetails: "Screen and Panel Details",
      productDetailsHeader: "Product Details",
      displayInfoHeader: "Display Information",
      paramHeader: "Parameter",
      valueHeader: "Value",
      pixelPitchLabel: "PX Pitch",
      brightnessLabel: "Brightness",
      ledTypeLabel: "LED Type",
      cabSizeLabel: "Cab. Size",
      cabResLabel: "Cab. Res.",
      modSizeLabel: "Mod. Size",
      modResLabel: "Mod. Res.",
      refreshRateLabel: "Refresh Rate",
      materialLabel: "Material",
      maintenanceLabel: "Maintenance",
      cabWeightLabel: "Weight/Cab.",
      typPowerLabel: "Typ. Power",
      maxPowerLabel: "Max Power",
      panelWidthLabel: "Panel Width",
      panelHeightLabel: "Panel Height",
      totalPxLabel: "Total Pixels",
      pxDensityLabel: "PX Density",
      totalWeightLabel: "Total Weight",
      totalPowerLabel: "Total Power",
      displayResLabel: "Display Res.",
      unitMm: "mm.",
      unitHz: "Hz",
      unitCdSqm: "cd/m²",
      modeQty: "Cabinet Mode",
      modeSize: "Meter Mode (W*H)",
      qtyWPlaceholder: "e.g. 5",
      qtyHPlaceholder: "e.g. 4",
      widthPlaceholder: "Width (m)",
      heightPlaceholder: "Height (m)",
      customPricePlaceholder: "e.g. 3000",
      customInstallPlaceholder: "Empty = 0",
      qtyPlaceholder: "Qty",
      unitWidth: "Width (Meter)",
      unitHeight: "Height (Meter)",
      calcNoteTitle: "Note:",
      calcNoteDesc: "The above price includes installation and other related expenses. However, this is only a preliminary estimate and may change according to site details and additional conditions.",
    },
  };
})();
