(function () {
  window.DEFAULT_DATA = {
    UIR: {
      w: 640, h: 480, weight: 7.8, type: 'indoor',
      items: [
        { name: 'UIRx 1.25', rw: 512, rh: 384, max: 522, avg: 157, price: 0 },
        { name: 'UIRx 1.5', rw: 416, rh: 312, max: 386, avg: 116, price: 50_000 },
        { name: 'UIRx 1.8', rw: 348, rh: 261, max: 432, avg: 130, price: 35_000 },
        { name: 'UIRx 2.0', rw: 320, rh: 240, max: 408, avg: 122, price: 0 },
        { name: 'UIRx 2.5', rw: 256, rh: 192, max: 356, avg: 107, price: 25_000 },
        { name: 'UIRx 3.0', rw: 208, rh: 156, max: 295, avg: 89, price: 0 },
        { name: 'UIRx 4.0', rw: 160, rh: 120, max: 331, avg: 99, price: 20_000 },
        { name: 'UIRc 1.5', rw: 416, rh: 312, max: 386, avg: 116, price: 69_000 },
        { name: 'UIRc 1.8', rw: 348, rh: 261, max: 432, avg: 130, price: 52_000 }
      ]
    },
    UOS: {
      w: 960, h: 960, weight: 26.5, type: 'outdoor',
      items: [
        { name: 'UOS 4', rw: 240, rh: 240, max: 675, avg: 203, price: 0 },
        { name: 'UOS 5', rw: 192, rh: 192, max: 712, avg: 214, price: 30_000 },
        { name: 'UOS 8', rw: 120, rh: 120, max: 847, avg: 254, price: 0 },
        { name: 'UOS 10', rw: 96, rh: 96, max: 756, avg: 227, price: 28_000 }
      ]
    },
    CIH: {
      w: 600, h: 337.5, weight: 4.0, type: 'indoor',
      items: [
        { name: 'CIH 1.2', rw: 480, rh: 270, max: 350, avg: 150, price: 0 },
        { name: 'CIH 1.5', rw: 384, rh: 216, max: 350, avg: 125, price: 0 },
        { name: 'CIH 1.8', rw: 320, rh: 180, max: 350, avg: 115, price: 0 }
      ]
    },
    controllers: [
      { name: 'A2K', load: 2_000_000, price: 15_000 },
      { name: 'A4K', load: 8_800_000, price: 20_000 },
      { name: 'A35', load: 650_000, price: 0 },
      { name: 'A40', load: 650_000, price: 0 },
      { name: 'A100', load: 1_300_000, price: 25_000 },
      { name: 'A200', load: 2_300_000, price: 30_000 },
      { name: 'A500', load: 5_200_000, price: 60_000 },
      { name: 'A800', load: 8_800_000, price: 110_000 },
      { name: 'X2s', load: 1_300_000, price: 25_000 },
      { name: 'X4m', load: 2_600_000, price: 20_000 },
      { name: 'X4E', load: 2_600_000, price: 40_000 },
      { name: 'X4E-W', load: 2_600_000, price: 55_000 },
      { name: 'X6', load: 3_930_000, price: 45_000 },
      { name: 'X7', load: 5_240_000, price: 50_000 },
      { name: 'X8E', load: 5_240_000, price: 70_000 },
      { name: 'X8M', load: 5_240_000, price: 80_000 },
      { name: 'X12M', load: 7_860_000, price: 65_000 },
      { name: 'X16E', load: 10_480_000, price: 110_000 },
      { name: 'X16PRO', load: 10_480_000, price: 140_000 },
      { name: 'X20', load: 13_100_000, price: 110_000 },
      { name: 'X20M', load: 13_100_000, price: 200_000 },
      { name: 'VX20', load: 13_100_000, price: 250_000 },
      { name: 'VX10', load: 6_500_000, price: 110_000 },
      { name: 'VX6', load: 3_900_000, price: 80_000 },
      { name: 'AX08', load: 5_240_000, price: 67_000 },
      { name: 'AX06', load: 3_930_000, price: 49_000 }
    ],
    accessories: [
      { name: 'SL10', price: 15_000 }
    ]
  };

  window.I18N = {
    th: {
      appTitle: 'RAZR LED Solution Calculator Pro',
      subtitle: 'คำนวณสเปก, ราคา, และจัดการสินค้าได้จากหน้า Admin',
      adminLogin: 'Login Admin',
      adminLogout: 'ออกจากระบบ',
      adminOn: 'ล็อกอินแล้ว',
      adminOff: 'ยังไม่ล็อกอิน',
      tab1: 'UIRx/c (640x480)',
      tab2: 'UOSx (960x960)',
      tab3: 'CIH (600x337.5)',
      selectLed: 'เลือกรุ่น LED Display',
      qtyW: 'จำนวนตู้ (แนวนอน)',
      qtyH: 'จำนวนตู้ (แนวตั้ง)',
      controller: 'เลือก Controller',
      calcAgain: 'คำนวณใหม่',
      refresh: 'รีเฟรชข้อมูล',
      recText: 'ระบบแนะนำรุ่นที่เหมาะสม',
      productPrice: 'ค่าสินค้า LED',
      installPrice: 'ค่าติดตั้งโดยประมาณ',
      total: 'ราคารวมสุทธิ',
      notQuoted: 'รอใบเสนอราคา',
      notQuoted2: 'รอเสนอราคา',
      weight: 'น้ำหนักจอรวม',
      pixels: 'จำนวนพิกเซลรวม',
      resolution: 'ความละเอียด',
      screenSize: 'ขนาดจอ (กว้าง x สูง)',
      area: 'พื้นที่จอภาพ',
      power: 'การกินไฟ (Typical / Max)',
      amps: 'กระแสไฟฟ้า (รวมกระแสเกิน 1.25x)',
      elecCost: 'ค่าไฟโดยประมาณ (5 บาท/หน่วย)',
      controllerPrice: 'ค่า Controller',
      adminTitle: 'Admin: จัดการ Master Data',
      adminSub: 'แก้ไขสินค้า/Controller ได้ทันที และบันทึกลงฐานข้อมูลของเบราว์เซอร์',
      reset: 'รีเซ็ตเป็นค่าเริ่มต้น',
      saveAll: 'บันทึกทั้งหมด',
      addRow: '+ เพิ่มแถวใหม่',
      targetGroup: 'เลือกหมวดที่ต้องการแก้ไข',
      name: 'รุ่น',
      rw: 'Res W',
      rh: 'Res H',
      max: 'Max W/m²',
      avg: 'Avg W/m²',
      pricePerCab: 'ราคา/ตู้',
      controllerName: 'ชื่อรุ่น',
      load: 'Load (pixels)',
      price: 'ราคา',
      delete: 'ลบ',
      confirmDelete: 'ต้องการลบรายการนี้ใช่ไหม',
      confirmDeleteCon: 'ต้องการลบ Controller นี้ใช่ไหม',
      confirmReset: 'ต้องการรีเซ็ตข้อมูลทั้งหมดกลับเป็นค่าเริ่มต้นหรือไม่?',
      saved: 'บันทึกข้อมูลเรียบร้อย',
      resetDone: 'รีเซ็ตเรียบร้อย',
      loginTitle: 'Admin Login',
      loginDesc: 'ล็อกอินนี้เก็บไว้ในโค้ด ไม่ต้องใช้ฐานข้อมูล',
      username: 'Username',
      password: 'Password',
      loginBtn: 'เข้าสู่ระบบ',
      cancel: 'ยกเลิก',
      loginOk: 'เข้าสู่ระบบสำเร็จ',
      loginFail: 'Username หรือ Password ไม่ถูกต้อง',
      lang: 'ภาษา',
      theme: 'ธีม',
      dark: 'มืด',
      light: 'สว่าง',
      openAdmin: 'ไปหน้า Admin',
      backHome: 'กลับหน้า Calculator',
      autoSave: 'บันทึกอัตโนมัติ',
      recommend: 'แนะนำ:',
      noEnough: 'Controller ไม่พอสำหรับขนาดนี้'
    },
    en: {
      appTitle: 'RAZR LED Solution Calculator Pro',
      subtitle: 'Calculate specs, pricing, and manage products from Admin',
      adminLogin: 'Admin Login',
      adminLogout: 'Logout',
      adminOn: 'Logged in',
      adminOff: 'Not logged in',
      tab1: 'UIRx/c (640x480)',
      tab2: 'UOSx (960x960)',
      tab3: 'CIH (600x337.5)',
      selectLed: 'Select LED Display Model',
      qtyW: 'Cabinet Qty (Horizontal)',
      qtyH: 'Cabinet Qty (Vertical)',
      controller: 'Select Controller',
      calcAgain: 'Recalculate',
      refresh: 'Refresh Data',
      recText: 'Recommended controller',
      productPrice: 'LED Product Price',
      installPrice: 'Estimated Installation',
      total: 'Grand Total',
      notQuoted: 'Quote required',
      notQuoted2: 'Quote required',
      weight: 'Total Weight',
      pixels: 'Total Pixels',
      resolution: 'Resolution',
      screenSize: 'Screen Size (W x H)',
      area: 'Screen Area',
      power: 'Power (Typical / Max)',
      amps: 'Current Draw (1.25x Overcurrent)',
      elecCost: 'Electricity Cost (5 THB/unit)',
      controllerPrice: 'Controller Price',
      adminTitle: 'Admin: Master Data Management',
      adminSub: 'Edit products/controllers instantly and store them in browser database',
      reset: 'Reset to Default',
      saveAll: 'Save All',
      addRow: '+ Add Row',
      targetGroup: 'Select group to edit',
      name: 'Model',
      rw: 'Res W',
      rh: 'Res H',
      max: 'Max W/m²',
      avg: 'Avg W/m²',
      pricePerCab: 'Price/Cabinet',
      controllerName: 'Model Name',
      load: 'Load (pixels)',
      price: 'Price',
      delete: 'Delete',
      confirmDelete: 'Delete this item?',
      confirmDeleteCon: 'Delete this controller?',
      confirmReset: 'Reset all data to default?',
      saved: 'Saved successfully',
      resetDone: 'Reset complete',
      loginTitle: 'Admin Login',
      loginDesc: 'This login is coded in the app. No database needed.',
      username: 'Username',
      password: 'Password',
      loginBtn: 'Sign in',
      cancel: 'Cancel',
      loginOk: 'Login successful',
      loginFail: 'Incorrect username or password',
      lang: 'Language',
      theme: 'Theme',
      dark: 'Dark',
      light: 'Light',
      openAdmin: 'Open Admin',
      backHome: 'Back to Calculator',
      autoSave: 'Auto-saved',
      recommend: 'Recommended:',
      noEnough: 'Controller capacity is not enough'
    }
  };
})();
